[profiles]
[[miami]]
palette = "#000000:#FF4C8B:#7FFFD4:#FFD84C:#00FFA8:#D36CFF:#47CFFF:#f7f1ff:#69676c:#FF4C8B:#7FFFD4:#FFD84C:#00FFA8:#D36CFF:#47CFFF:#f7f1ff"
background_image = None
use_system_font = False
cursor_color = "#f7f1ff"
foreground_color = "#f7f1ff"
font = "Monospace 11"
background_color = "#000000"
