[profiles]
[[paris]]
palette = "#1a0a30:#fc618d:#7bd88f:#fce566:#a3f3ff:#c4bdff:#a3f3ff:#1a0a30:#c4bdff:#fc618d:#7bd88f:#fce566:#a3f3ff:#c4bdff:#a3f3ff:#f7f1ff"
background_image = None
use_system_font = False
cursor_color = "#f7f1ff"
foreground_color = "#f7f1ff"
font = "Monospace 11"
background_color = "#1a0a30"
