# helsinki — Spaceship prompt theme
# Generated from colors.md — canonical mapping

# Order
SPACESHIP_PROMPT_ORDER=(
  user
  host
  dir
  git
  exec_time
  exit_code
  line_sep
  char
)

SPACESHIP_RPROMPT_ORDER=(
  time
  battery
)

# Prefix / Suffix
SPACESHIP_PROMPT_FIRST_PREFIX_SHOW=true
SPACESHIP_PROMPT_DEFAULT_PREFIX=""
SPACESHIP_PROMPT_DEFAULT_SUFFIX=""

# User
SPACESHIP_USER_SHOW=always
SPACESHIP_USER_PREFIX=""
SPACESHIP_USER_SUFFIX=" "
SPACESHIP_USER_COLOR="#2e70ad"
SPACESHIP_USER_COLOR_ROOT="#1faa9e"

# Host
SPACESHIP_HOST_SHOW=always
SPACESHIP_HOST_PREFIX="@"
SPACESHIP_HOST_SUFFIX=" "
SPACESHIP_HOST_COLOR="#544d40"

# Directory
SPACESHIP_DIR_PREFIX=""
SPACESHIP_DIR_SUFFIX=" "
SPACESHIP_DIR_COLOR="#bd4c3d"
SPACESHIP_DIR_TRUNC=2
SPACESHIP_DIR_TRUNC_REPO=true

# Git
SPACESHIP_GIT_BRANCH_PREFIX=""
SPACESHIP_GIT_BRANCH_SUFFIX=" "
SPACESHIP_GIT_BRANCH_COLOR="#544d40"
SPACESHIP_GIT_STATUS_PREFIX=""
SPACESHIP_GIT_STATUS_SUFFIX=" "
SPACESHIP_GIT_STATUS_COLOR="#544d40"
SPACESHIP_GIT_STATUS_UNTRACKED="?"
SPACESHIP_GIT_STATUS_ADDED="+"
SPACESHIP_GIT_STATUS_MODIFIED="!"
SPACESHIP_GIT_STATUS_DELETED="✘"

# Execution time
SPACESHIP_EXEC_TIME_ELAPSED=2
SPACESHIP_EXEC_TIME_PREFIX="("
SPACESHIP_EXEC_TIME_SUFFIX=") "
SPACESHIP_EXEC_TIME_COLOR="#bd4c3d"

# Exit code
SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_EXIT_CODE_PREFIX=""
SPACESHIP_EXIT_CODE_SUFFIX=" "
SPACESHIP_EXIT_CODE_COLOR="#1faa9e"

# Time (right prompt)
SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_PREFIX=""
SPACESHIP_TIME_SUFFIX=" "
SPACESHIP_TIME_COLOR="#1faa9e"
SPACESHIP_TIME_FORMAT="%R"

# Battery (right prompt)
SPACESHIP_BATTERY_SHOW=true
SPACESHIP_BATTERY_PREFIX=""
SPACESHIP_BATTERY_SUFFIX=" "
SPACESHIP_BATTERY_COLOR="#2e70ad"
SPACESHIP_BATTERY_CHARGING_COLOR="#2e70ad"
SPACESHIP_BATTERY_DISCHARGING_COLOR="#1faa9e"

# Character
SPACESHIP_CHAR_PREFIX=""
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_COLOR_SUCCESS="#733d9a"
SPACESHIP_CHAR_COLOR_FAILURE="#1faa9e"
SPACESHIP_CHAR_SYMBOL="❯"
SPACESHIP_CHAR_SYMBOL_ROOT="#"
