format = """
[](fg:#000000)\
$username\
$hostname\
[](bg:#000000 fg:#aaaaaa)\
$os\
[>](fg:#aaaaaa)\
[](fg:#999999 bg:#aaaaaa)\
$time\
[](bg:#999999 fg:#cccccc)\
$directory\
[>](fg:#cccccc)\
$nodejs\
$rust\
$golang\
$php\
$java\
$julia\
$ocaml\
$zig\
$lua\
$python\
$ruby\
$dart\
$c\
[>](fg:#ffffff)\
$git_branch\
$git_status\
[>](fg:#cccccc)\
$cmd_duration\
[>](fg:#999999)\
$status\
[>](fg:#dddddd)\
$battery\
\n$character"""

[username]
style_user = "fg:#dddddd bg:#000000"
style_root = "fg:#999999 bg:#000000"
format = "[ $user ]($style)"
show_always = true

[hostname]
style = "fg:#ffffff bg:#000000"
format = "[@$hostname ]($style)"
ssh_only = false

[directory]
style = "fg:#000000 bg:#cccccc"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "

[os]
disabled = false
style = "fg:#aaaaaa"

[os.symbols]
Windows = " 󰍲 "
Ubuntu = " 󰕈 "
SUSE = "  "
Raspbian = " 󰐿 "
Mint = " 󰣭 "
Macos = " 󰀵 "
Manjaro = "  "
Linux = " 󰌽 "
Gentoo = " 󰣨 "
Fedora = " 󰣛 "
Alpine = "  "
Amazon = "  "
Android = "  "
Arch = " 󰣇 "
Artix = " 󰣇 "
CentOS = "  "
Debian = " 󰣚 "
Redhat = " 󱄛 "
RedHatEnterprise = " 󱄛 "
Pop = "  "

[git_branch]
symbol = ""
style = "fg:#ffffff"
format = "[[ $symbol $branch ](fg:#ffffff)]($style)"

[git_status]
style = "fg:#ffffff"
format = "[[($all_status$ahead_behind )](fg:#ffffff)]($style)"

[git_metrics]
disabled = true

[nodejs]
symbol = ""
style = "fg:#cccccc"
format = "[[ $symbol ($version) ](fg:#cccccc)]($style)"

[rust]
symbol = ""
style = "fg:#cccccc"
format = "[[ $symbol ($version) ](fg:#cccccc)]($style)"

[golang]
symbol = ""
style = "fg:#cccccc"
format = "[[ $symbol ($version) ](fg:#cccccc)]($style)"

[php]
symbol = ""
style = "fg:#cccccc"
format = "[[ $symbol ($version) ](fg:#cccccc)]($style)"

[java]
symbol = ""
style = "fg:#cccccc"
format = "[[ $symbol ($version) ](fg:#cccccc)]($style)"

[julia]
symbol = ""
style = "fg:#cccccc"
format = "[[ $symbol ($version) ](fg:#cccccc)]($style)"

[ocaml]
symbol = ""
style = "fg:#cccccc"
format = "[[ $symbol ($version) ](fg:#cccccc)]($style)"

[zig]
symbol = ""
style = "fg:#cccccc"
format = "[[ $symbol ($version) ](fg:#cccccc)]($style)"

[lua]
symbol = ""
style = "fg:#cccccc"
format = "[[ $symbol ($version) ](fg:#cccccc)]($style)"

[python]
symbol = ""
style = "fg:#cccccc"
format = "[[ $symbol ($version) ](fg:#cccccc)]($style)"

[ruby]
symbol = ""
style = "fg:#cccccc"
format = "[[ $symbol ($version) ](fg:#cccccc)]($style)"

[dart]
symbol = ""
style = "fg:#cccccc"
format = "[[ $symbol ($version) ](fg:#cccccc)]($style)"

[c]
symbol = "󰬊"
style = "fg:#cccccc"
format = "[[ $symbol ($version) ](fg:#cccccc)]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:#999999"
format = "[[  $time ](fg:#000000 bg:#999999)]($style)"

[cmd_duration]
min_time = 800
style = "fg:#cccccc"
format = "[[  $duration ](fg:#cccccc)]($style)"

[status]
disabled = false
style = "fg:#999999"
format = "[[ $status ](fg:#999999)]($style)"

[memory_usage]
disabled = true

[battery]
disabled = false
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
format = "[[ $symbol $percentage ](fg:#dddddd)]($style)"

[[battery.display]]
threshold = 20
style = "fg:#999999"

[[battery.display]]
threshold = 100
style = "fg:#dddddd"

[character]
success_symbol = "[>](bold #bbbbbb)"
error_symbol = "[>](bold #999999)"
