format = """
[](fg:#200b0a)\
$username\
$hostname\
[](bg:#200b0a fg:#ff9999)\
$os\
[>](fg:#ff9999)\
[](fg:#fc618d bg:#ff9999)\
$time\
[](bg:#fc618d fg:#47e6ff)\
$directory\
[>](fg:#47e6ff)\
$nodejs\
$rust\
$golang\
$php\
$java\
$julia\
$ocaml\
$zig\
$lua\
$python\
$ruby\
$dart\
$c\
[>](fg:#f7f1ff)\
$git_branch\
$git_status\
[>](fg:#47e6ff)\
$cmd_duration\
[>](fg:#fc618d)\
$status\
[>](fg:#ffed89)\
$battery\
\n$character"""

[username]
style_user = "fg:#ffed89 bg:#200b0a"
style_root = "fg:#fc618d bg:#200b0a"
format = "[ $user ]($style)"
show_always = true

[hostname]
style = "fg:#f7f1ff bg:#200b0a"
format = "[@$hostname ]($style)"
ssh_only = false

[directory]
style = "fg:#200b0a bg:#47e6ff"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "

[os]
disabled = false
style = "fg:#ff9999"

[os.symbols]
Windows = " 󰍲 "
Ubuntu = " 󰕈 "
SUSE = "  "
Raspbian = " 󰐿 "
Mint = " 󰣭 "
Macos = " 󰀵 "
Manjaro = "  "
Linux = " 󰌽 "
Gentoo = " 󰣨 "
Fedora = " 󰣛 "
Alpine = "  "
Amazon = "  "
Android = "  "
Arch = " 󰣇 "
Artix = " 󰣇 "
CentOS = "  "
Debian = " 󰣚 "
Redhat = " 󱄛 "
RedHatEnterprise = " 󱄛 "
Pop = "  "

[git_branch]
symbol = ""
style = "fg:#f7f1ff"
format = "[[ $symbol $branch ](fg:#f7f1ff)]($style)"

[git_status]
style = "fg:#f7f1ff"
format = "[[($all_status$ahead_behind )](fg:#f7f1ff)]($style)"

[git_metrics]
disabled = true

[nodejs]
symbol = ""
style = "fg:#47e6ff"
format = "[[ $symbol ($version) ](fg:#47e6ff)]($style)"

[rust]
symbol = ""
style = "fg:#47e6ff"
format = "[[ $symbol ($version) ](fg:#47e6ff)]($style)"

[golang]
symbol = ""
style = "fg:#47e6ff"
format = "[[ $symbol ($version) ](fg:#47e6ff)]($style)"

[php]
symbol = ""
style = "fg:#47e6ff"
format = "[[ $symbol ($version) ](fg:#47e6ff)]($style)"

[java]
symbol = ""
style = "fg:#47e6ff"
format = "[[ $symbol ($version) ](fg:#47e6ff)]($style)"

[julia]
symbol = ""
style = "fg:#47e6ff"
format = "[[ $symbol ($version) ](fg:#47e6ff)]($style)"

[ocaml]
symbol = ""
style = "fg:#47e6ff"
format = "[[ $symbol ($version) ](fg:#47e6ff)]($style)"

[zig]
symbol = ""
style = "fg:#47e6ff"
format = "[[ $symbol ($version) ](fg:#47e6ff)]($style)"

[lua]
symbol = ""
style = "fg:#47e6ff"
format = "[[ $symbol ($version) ](fg:#47e6ff)]($style)"

[python]
symbol = ""
style = "fg:#47e6ff"
format = "[[ $symbol ($version) ](fg:#47e6ff)]($style)"

[ruby]
symbol = ""
style = "fg:#47e6ff"
format = "[[ $symbol ($version) ](fg:#47e6ff)]($style)"

[dart]
symbol = ""
style = "fg:#47e6ff"
format = "[[ $symbol ($version) ](fg:#47e6ff)]($style)"

[c]
symbol = "󰬊"
style = "fg:#47e6ff"
format = "[[ $symbol ($version) ](fg:#47e6ff)]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:#fc618d"
format = "[[  $time ](fg:#200b0a bg:#fc618d)]($style)"

[cmd_duration]
min_time = 800
style = "fg:#47e6ff"
format = "[[  $duration ](fg:#47e6ff)]($style)"

[status]
disabled = false
style = "fg:#fc618d"
format = "[[ $status ](fg:#fc618d)]($style)"

[memory_usage]
disabled = true

[battery]
disabled = false
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
format = "[[ $symbol $percentage ](fg:#ffed89)]($style)"

[[battery.display]]
threshold = 20
style = "fg:#fc618d"

[[battery.display]]
threshold = 100
style = "fg:#ffed89"

[character]
success_symbol = "[>](bold #7bd88f)"
error_symbol = "[>](bold #fc618d)"
