format = """
[](fg:#363537)\
$username\
$hostname\
[](bg:#948ae3 fg:#363537)\
$os\
[](bg:#fc618d fg:#948ae3)\
$time\
[](fg:#fc618d bg:#5ad4e6)\
$directory\
[](fg:#5ad4e6 bg:#69676c)\
$nodejs\
$rust\
$golang\
$php\
$java\
$julia\
$ocaml\
$zig\
$lua\
$python\
$ruby\
$dart\
$c\
[](fg:#69676c bg:#363537)\
[](fg:#5ad4e6 bg:#363537)\
$git_branch\
$git_status\
[](fg:#363537)\
$cmd_duration\
$status\
$battery\
\n$character"""

[username]
style_user = "fg:#e5ff9d bg:#363537"
style_root = "fg:#fc618d bg:#363537"
format = "[ $user ]($style)"
show_always = true

[hostname]
style = "fg:#f7f1ff bg:#363537"
format = "[@$hostname ]($style)"
ssh_only = false

[directory]
style = "fg:#363537 bg:#5ad4e6"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "

[os]
disabled = false
style = "bg:#948ae3 fg:#363537"

[os.symbols]
Windows = " 󰍲 "
Ubuntu = " 󰕈 "
SUSE = "  "
Raspbian = " 󰐿 "
Mint = " 󰣭 "
Macos = " 󰀵 "
Manjaro = "  "
Linux = " 󰌽 "
Gentoo = " 󰣨 "
Fedora = " 󰣛 "
Alpine = "  "
Amazon = "  "
Android = "  "
Arch = " 󰣇 "
Artix = " 󰣇 "
CentOS = "  "
Debian = " 󰣚 "
Redhat = " 󱄛 "
RedHatEnterprise = " 󱄛 "
Pop = "  "


[git_branch]
symbol = ""
style = "bg:#363537"
format = "[[ $symbol $branch ](fg:#f7f1ff bg:#363537)]($style)"

[git_status]
style = "bg:#363537"
format = "[[($all_status$ahead_behind )](fg:#f7f1ff bg:#363537)]($style)"

[git_metrics]
disabled = true

[nodejs]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#5ad4e6 bg:#69676c)]($style)"

[rust]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#5ad4e6 bg:#69676c)]($style)"

[golang]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#5ad4e6 bg:#69676c)]($style)"

[php]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#5ad4e6 bg:#69676c)]($style)"

[java]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#5ad4e6 bg:#69676c)]($style)"

[julia]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#5ad4e6 bg:#69676c)]($style)"

[ocaml]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#5ad4e6 bg:#69676c)]($style)"

[zig]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#5ad4e6 bg:#69676c)]($style)"

[lua]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#5ad4e6 bg:#69676c)]($style)"

[python]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#5ad4e6 bg:#69676c)]($style)"

[ruby]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#5ad4e6 bg:#69676c)]($style)"

[dart]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#5ad4e6 bg:#69676c)]($style)"

[c]
symbol = "󰬊"
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#5ad4e6 bg:#69676c)]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:#fc618d"
format = "[[  $time ](fg:#363537 bg:#fc618d)]($style)"

[cmd_duration]
min_time = 800
style = "bg:#363537"
format = "[[  $duration ](fg:#5ad4e6 bg:#363537)]($style)"

[status]
disabled = false
style = "bg:#363537"
format = "[[ $status ](fg:#fc618d bg:#363537)]($style)"

[memory_usage]
disabled = true

[battery]
disabled = false
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
format = "[[ $symbol $percentage ](fg:#e5ff9d bg:#363537)]($style)"

[[battery.display]]
threshold = 20
style = "fg:#fc618d bg:#363537"

[[battery.display]]
threshold = 100
style = "fg:#e5ff9d bg:#363537"

[character]
success_symbol = "[❯](bold #7bd88f)"
error_symbol = "[❯](bold #fc618d)"
