format = """
[](fg:#ffffff)\
$username\
$hostname\
[](bg:#ffffff fg:#777777)\
$os\
[>](fg:#777777)\
[](fg:#333333 bg:#777777)\
$time\
[](bg:#333333 fg:#888888)\
$directory\
[>](fg:#888888)\
$nodejs\
$rust\
$golang\
$php\
$java\
$julia\
$ocaml\
$zig\
$lua\
$python\
$ruby\
$dart\
$c\
[>](fg:#333333)\
$git_branch\
$git_status\
[>](fg:#888888)\
$cmd_duration\
[>](fg:#333333)\
$status\
[>](fg:#555555)\
$battery\
\n$character"""

[username]
style_user = "fg:#555555 bg:#ffffff"
style_root = "fg:#333333 bg:#ffffff"
format = "[ $user ]($style)"
show_always = true

[hostname]
style = "fg:#333333 bg:#ffffff"
format = "[@$hostname ]($style)"
ssh_only = false

[directory]
style = "fg:#ffffff bg:#888888"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "

[os]
disabled = false
style = "fg:#777777"

[os.symbols]
Windows = " 󰍲 "
Ubuntu = " 󰕈 "
SUSE = "  "
Raspbian = " 󰐿 "
Mint = " 󰣭 "
Macos = " 󰀵 "
Manjaro = "  "
Linux = " 󰌽 "
Gentoo = " 󰣨 "
Fedora = " 󰣛 "
Alpine = "  "
Amazon = "  "
Android = "  "
Arch = " 󰣇 "
Artix = " 󰣇 "
CentOS = "  "
Debian = " 󰣚 "
Redhat = " 󱄛 "
RedHatEnterprise = " 󱄛 "
Pop = "  "

[git_branch]
symbol = ""
style = "fg:#333333"
format = "[[ $symbol $branch ](fg:#333333)]($style)"

[git_status]
style = "fg:#333333"
format = "[[($all_status$ahead_behind )](fg:#333333)]($style)"

[git_metrics]
disabled = true

[nodejs]
symbol = ""
style = "fg:#888888"
format = "[[ $symbol ($version) ](fg:#888888)]($style)"

[rust]
symbol = ""
style = "fg:#888888"
format = "[[ $symbol ($version) ](fg:#888888)]($style)"

[golang]
symbol = ""
style = "fg:#888888"
format = "[[ $symbol ($version) ](fg:#888888)]($style)"

[php]
symbol = ""
style = "fg:#888888"
format = "[[ $symbol ($version) ](fg:#888888)]($style)"

[java]
symbol = ""
style = "fg:#888888"
format = "[[ $symbol ($version) ](fg:#888888)]($style)"

[julia]
symbol = ""
style = "fg:#888888"
format = "[[ $symbol ($version) ](fg:#888888)]($style)"

[ocaml]
symbol = ""
style = "fg:#888888"
format = "[[ $symbol ($version) ](fg:#888888)]($style)"

[zig]
symbol = ""
style = "fg:#888888"
format = "[[ $symbol ($version) ](fg:#888888)]($style)"

[lua]
symbol = ""
style = "fg:#888888"
format = "[[ $symbol ($version) ](fg:#888888)]($style)"

[python]
symbol = ""
style = "fg:#888888"
format = "[[ $symbol ($version) ](fg:#888888)]($style)"

[ruby]
symbol = ""
style = "fg:#888888"
format = "[[ $symbol ($version) ](fg:#888888)]($style)"

[dart]
symbol = ""
style = "fg:#888888"
format = "[[ $symbol ($version) ](fg:#888888)]($style)"

[c]
symbol = "󰬊"
style = "fg:#888888"
format = "[[ $symbol ($version) ](fg:#888888)]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:#333333"
format = "[[  $time ](fg:#ffffff bg:#333333)]($style)"

[cmd_duration]
min_time = 800
style = "fg:#888888"
format = "[[  $duration ](fg:#888888)]($style)"

[status]
disabled = false
style = "fg:#333333"
format = "[[ $status ](fg:#333333)]($style)"

[memory_usage]
disabled = true

[battery]
disabled = false
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
format = "[[ $symbol $percentage ](fg:#555555)]($style)"

[[battery.display]]
threshold = 20
style = "fg:#333333"

[[battery.display]]
threshold = 100
style = "fg:#555555"

[character]
success_symbol = "[>](bold #444444)"
error_symbol = "[>](bold #333333)"
