format = """
[](fg:#333333)\
$username\
$hostname\
[](bg:#6633cc fg:#333333)\
$os\
[](bg:#cc0033 fg:#6633cc)\
$time\
[](fg:#cc0033 bg:#0099cc)\
$directory\
[](fg:#0099cc bg:#666666)\
$nodejs\
$rust\
$golang\
$php\
$java\
$julia\
$ocaml\
$zig\
$lua\
$python\
$ruby\
$dart\
$c\
[](fg:#666666 bg:#333333)\
[](fg:#0099cc bg:#333333)\
$git_branch\
$git_status\
[](fg:#333333)\
$cmd_duration\
$status\
$battery\
\n$character"""

[username]
style_user = "fg:#b8860b bg:#333333"
style_root = "fg:#cc0033 bg:#333333"
format = "[ $user ]($style)"
show_always = true

[hostname]
style = "fg:#1a1a1a bg:#333333"
format = "[@$hostname ]($style)"
ssh_only = false

[directory]
style = "fg:#333333 bg:#0099cc"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "

[os]
disabled = false
style = "bg:#6633cc fg:#333333"

[os.symbols]
Windows = " 󰍲 "
Ubuntu = " 󰕈 "
SUSE = "  "
Raspbian = " 󰐿 "
Mint = " 󰣭 "
Macos = " 󰀵 "
Manjaro = "  "
Linux = " 󰌽 "
Gentoo = " 󰣨 "
Fedora = " 󰣛 "
Alpine = "  "
Amazon = "  "
Android = "  "
Arch = " 󰣇 "
Artix = " 󰣇 "
CentOS = "  "
Debian = " 󰣚 "
Redhat = " 󱄛 "
RedHatEnterprise = " 󱄛 "
Pop = "  "


[git_branch]
symbol = ""
style = "bg:#333333"
format = "[[ $symbol $branch ](fg:#1a1a1a bg:#333333)]($style)"

[git_status]
style = "bg:#333333"
format = "[[($all_status$ahead_behind )](fg:#1a1a1a bg:#333333)]($style)"

[git_metrics]
disabled = true

[nodejs]
symbol = ""
style = "bg:#666666"
format = "[[ $symbol ($version) ](fg:#0099cc bg:#666666)]($style)"

[rust]
symbol = ""
style = "bg:#666666"
format = "[[ $symbol ($version) ](fg:#0099cc bg:#666666)]($style)"

[golang]
symbol = ""
style = "bg:#666666"
format = "[[ $symbol ($version) ](fg:#0099cc bg:#666666)]($style)"

[php]
symbol = ""
style = "bg:#666666"
format = "[[ $symbol ($version) ](fg:#0099cc bg:#666666)]($style)"

[java]
symbol = ""
style = "bg:#666666"
format = "[[ $symbol ($version) ](fg:#0099cc bg:#666666)]($style)"

[julia]
symbol = ""
style = "bg:#666666"
format = "[[ $symbol ($version) ](fg:#0099cc bg:#666666)]($style)"

[ocaml]
symbol = ""
style = "bg:#666666"
format = "[[ $symbol ($version) ](fg:#0099cc bg:#666666)]($style)"

[zig]
symbol = ""
style = "bg:#666666"
format = "[[ $symbol ($version) ](fg:#0099cc bg:#666666)]($style)"

[lua]
symbol = ""
style = "bg:#666666"
format = "[[ $symbol ($version) ](fg:#0099cc bg:#666666)]($style)"

[python]
symbol = ""
style = "bg:#666666"
format = "[[ $symbol ($version) ](fg:#0099cc bg:#666666)]($style)"

[ruby]
symbol = ""
style = "bg:#666666"
format = "[[ $symbol ($version) ](fg:#0099cc bg:#666666)]($style)"

[dart]
symbol = ""
style = "bg:#666666"
format = "[[ $symbol ($version) ](fg:#0099cc bg:#666666)]($style)"

[c]
symbol = "󰬊"
style = "bg:#666666"
format = "[[ $symbol ($version) ](fg:#0099cc bg:#666666)]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:#cc0033"
format = "[[  $time ](fg:#333333 bg:#cc0033)]($style)"

[cmd_duration]
min_time = 800
style = "bg:#333333"
format = "[[  $duration ](fg:#0099cc bg:#333333)]($style)"

[status]
disabled = false
style = "bg:#333333"
format = "[[ $status ](fg:#cc0033 bg:#333333)]($style)"

[memory_usage]
disabled = true

[battery]
disabled = false
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
format = "[[ $symbol $percentage ](fg:#b8860b bg:#333333)]($style)"

[[battery.display]]
threshold = 20
style = "fg:#cc0033 bg:#333333"

[[battery.display]]
threshold = 100
style = "fg:#b8860b bg:#333333"

[character]
success_symbol = "[❯](bold #009933)"
error_symbol = "[❯](bold #cc0033)"
