format = """
[](fg:#000000)\
$username\
$hostname\
[](bg:#000000 fg:#D36CFF)\
$os\
[>](fg:#D36CFF)\
[](fg:#FF4C8B bg:#D36CFF)\
$time\
[](bg:#FF4C8B fg:#47CFFF)\
$directory\
[>](fg:#47CFFF)\
$nodejs\
$rust\
$golang\
$php\
$java\
$julia\
$ocaml\
$zig\
$lua\
$python\
$ruby\
$dart\
$c\
[>](fg:#f7f1ff)\
$git_branch\
$git_status\
[>](fg:#47CFFF)\
$cmd_duration\
[>](fg:#FF4C8B)\
$status\
[>](fg:#FFD84C)\
$battery\
\n$character"""

[username]
style_user = "fg:#FFD84C bg:#000000"
style_root = "fg:#FF4C8B bg:#000000"
format = "[ $user ]($style)"
show_always = true

[hostname]
style = "fg:#f7f1ff bg:#000000"
format = "[@$hostname ]($style)"
ssh_only = false

[directory]
style = "fg:#000000 bg:#47CFFF"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "

[os]
disabled = false
style = "fg:#D36CFF"

[os.symbols]
Windows = " 󰍲 "
Ubuntu = " 󰕈 "
SUSE = "  "
Raspbian = " 󰐿 "
Mint = " 󰣭 "
Macos = " 󰀵 "
Manjaro = "  "
Linux = " 󰌽 "
Gentoo = " 󰣨 "
Fedora = " 󰣛 "
Alpine = "  "
Amazon = "  "
Android = "  "
Arch = " 󰣇 "
Artix = " 󰣇 "
CentOS = "  "
Debian = " 󰣚 "
Redhat = " 󱄛 "
RedHatEnterprise = " 󱄛 "
Pop = "  "

[git_branch]
symbol = ""
style = "fg:#f7f1ff"
format = "[[ $symbol $branch ](fg:#f7f1ff)]($style)"

[git_status]
style = "fg:#f7f1ff"
format = "[[($all_status$ahead_behind )](fg:#f7f1ff)]($style)"

[git_metrics]
disabled = true

[nodejs]
symbol = ""
style = "fg:#47CFFF"
format = "[[ $symbol ($version) ](fg:#47CFFF)]($style)"

[rust]
symbol = ""
style = "fg:#47CFFF"
format = "[[ $symbol ($version) ](fg:#47CFFF)]($style)"

[golang]
symbol = ""
style = "fg:#47CFFF"
format = "[[ $symbol ($version) ](fg:#47CFFF)]($style)"

[php]
symbol = ""
style = "fg:#47CFFF"
format = "[[ $symbol ($version) ](fg:#47CFFF)]($style)"

[java]
symbol = ""
style = "fg:#47CFFF"
format = "[[ $symbol ($version) ](fg:#47CFFF)]($style)"

[julia]
symbol = ""
style = "fg:#47CFFF"
format = "[[ $symbol ($version) ](fg:#47CFFF)]($style)"

[ocaml]
symbol = ""
style = "fg:#47CFFF"
format = "[[ $symbol ($version) ](fg:#47CFFF)]($style)"

[zig]
symbol = ""
style = "fg:#47CFFF"
format = "[[ $symbol ($version) ](fg:#47CFFF)]($style)"

[lua]
symbol = ""
style = "fg:#47CFFF"
format = "[[ $symbol ($version) ](fg:#47CFFF)]($style)"

[python]
symbol = ""
style = "fg:#47CFFF"
format = "[[ $symbol ($version) ](fg:#47CFFF)]($style)"

[ruby]
symbol = ""
style = "fg:#47CFFF"
format = "[[ $symbol ($version) ](fg:#47CFFF)]($style)"

[dart]
symbol = ""
style = "fg:#47CFFF"
format = "[[ $symbol ($version) ](fg:#47CFFF)]($style)"

[c]
symbol = "󰬊"
style = "fg:#47CFFF"
format = "[[ $symbol ($version) ](fg:#47CFFF)]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:#FF4C8B"
format = "[[  $time ](fg:#000000 bg:#FF4C8B)]($style)"

[cmd_duration]
min_time = 800
style = "fg:#47CFFF"
format = "[[  $duration ](fg:#47CFFF)]($style)"

[status]
disabled = false
style = "fg:#FF4C8B"
format = "[[ $status ](fg:#FF4C8B)]($style)"

[memory_usage]
disabled = true

[battery]
disabled = false
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
format = "[[ $symbol $percentage ](fg:#FFD84C)]($style)"

[[battery.display]]
threshold = 20
style = "fg:#FF4C8B"

[[battery.display]]
threshold = 100
style = "fg:#FFD84C"

[character]
success_symbol = "[>](bold #7FFFD4)"
error_symbol = "[>](bold #FF4C8B)"
