format = """
[](fg:#1A1A1A)\
$username\
$hostname\
[](bg:#FF9AA2 fg:#1A1A1A)\
$os\
[](bg:#FF5555 fg:#FF9AA2)\
$time\
[](fg:#FF5555 bg:#8BE9FD)\
$directory\
[](fg:#8BE9FD bg:#6272A4)\
$nodejs\
$rust\
$golang\
$php\
$java\
$julia\
$ocaml\
$zig\
$lua\
$python\
$ruby\
$dart\
$c\
[](fg:#6272A4 bg:#1A1A1A)\
[](fg:#8BE9FD bg:#1A1A1A)\
$git_branch\
$git_status\
[](fg:#1A1A1A)\
$cmd_duration\
$status\
$battery\
\n$character"""

[username]
style_user = "fg:#FFE4A3 bg:#1A1A1A"
style_root = "fg:#FF5555 bg:#1A1A1A"
format = "[ $user ]($style)"
show_always = true

[hostname]
style = "fg:#FFFFFF bg:#1A1A1A"
format = "[@$hostname ]($style)"
ssh_only = false

[directory]
style = "fg:#1A1A1A bg:#8BE9FD"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "

[os]
disabled = false
style = "bg:#FF9AA2 fg:#1A1A1A"

[os.symbols]
Windows = " 󰍲 "
Ubuntu = " 󰕈 "
SUSE = "  "
Raspbian = " 󰐿 "
Mint = " 󰣭 "
Macos = " 󰀵 "
Manjaro = "  "
Linux = " 󰌽 "
Gentoo = " 󰣨 "
Fedora = " 󰣛 "
Alpine = "  "
Amazon = "  "
Android = "  "
Arch = " 󰣇 "
Artix = " 󰣇 "
CentOS = "  "
Debian = " 󰣚 "
Redhat = " 󱄛 "
RedHatEnterprise = " 󱄛 "
Pop = "  "


[git_branch]
symbol = ""
style = "bg:#1A1A1A"
format = "[[ $symbol $branch ](fg:#FFFFFF bg:#1A1A1A)]($style)"

[git_status]
style = "bg:#1A1A1A"
format = "[[($all_status$ahead_behind )](fg:#FFFFFF bg:#1A1A1A)]($style)"

[git_metrics]
disabled = true

[nodejs]
symbol = ""
style = "bg:#6272A4"
format = "[[ $symbol ($version) ](fg:#8BE9FD bg:#6272A4)]($style)"

[rust]
symbol = ""
style = "bg:#6272A4"
format = "[[ $symbol ($version) ](fg:#8BE9FD bg:#6272A4)]($style)"

[golang]
symbol = ""
style = "bg:#6272A4"
format = "[[ $symbol ($version) ](fg:#8BE9FD bg:#6272A4)]($style)"

[php]
symbol = ""
style = "bg:#6272A4"
format = "[[ $symbol ($version) ](fg:#8BE9FD bg:#6272A4)]($style)"

[java]
symbol = ""
style = "bg:#6272A4"
format = "[[ $symbol ($version) ](fg:#8BE9FD bg:#6272A4)]($style)"

[julia]
symbol = ""
style = "bg:#6272A4"
format = "[[ $symbol ($version) ](fg:#8BE9FD bg:#6272A4)]($style)"

[ocaml]
symbol = ""
style = "bg:#6272A4"
format = "[[ $symbol ($version) ](fg:#8BE9FD bg:#6272A4)]($style)"

[zig]
symbol = ""
style = "bg:#6272A4"
format = "[[ $symbol ($version) ](fg:#8BE9FD bg:#6272A4)]($style)"

[lua]
symbol = ""
style = "bg:#6272A4"
format = "[[ $symbol ($version) ](fg:#8BE9FD bg:#6272A4)]($style)"

[python]
symbol = ""
style = "bg:#6272A4"
format = "[[ $symbol ($version) ](fg:#8BE9FD bg:#6272A4)]($style)"

[ruby]
symbol = ""
style = "bg:#6272A4"
format = "[[ $symbol ($version) ](fg:#8BE9FD bg:#6272A4)]($style)"

[dart]
symbol = ""
style = "bg:#6272A4"
format = "[[ $symbol ($version) ](fg:#8BE9FD bg:#6272A4)]($style)"

[c]
symbol = "󰬊"
style = "bg:#6272A4"
format = "[[ $symbol ($version) ](fg:#8BE9FD bg:#6272A4)]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:#FF5555"
format = "[[  $time ](fg:#1A1A1A bg:#FF5555)]($style)"

[cmd_duration]
min_time = 800
style = "bg:#1A1A1A"
format = "[[  $duration ](fg:#8BE9FD bg:#1A1A1A)]($style)"

[status]
disabled = false
style = "bg:#1A1A1A"
format = "[[ $status ](fg:#FF5555 bg:#1A1A1A)]($style)"

[memory_usage]
disabled = true

[battery]
disabled = false
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
format = "[[ $symbol $percentage ](fg:#FFE4A3 bg:#1A1A1A)]($style)"

[[battery.display]]
threshold = 20
style = "fg:#FF5555 bg:#1A1A1A"

[[battery.display]]
threshold = 100
style = "fg:#FFE4A3 bg:#1A1A1A"

[character]
success_symbol = "[❯](bold #B8E6A0)"
error_symbol = "[❯](bold #FF5555)"
