format = """
[](fg:#1b1b1bff)\
$username\
$hostname\
[](bg:#D36CFF fg:#1b1b1bff)\
$os\
[](bg:#FF4C8B fg:#D36CFF)\
$time\
[](fg:#FF4C8B bg:#47CFFF)\
$directory\
[](fg:#47CFFF bg:#69676c)\
$nodejs\
$rust\
$golang\
$php\
$java\
$julia\
$ocaml\
$zig\
$lua\
$python\
$ruby\
$dart\
$c\
[](fg:#69676c bg:#1b1b1bff)\
[](fg:#47CFFF bg:#1b1b1bff)\
$git_branch\
$git_status\
[](fg:#1b1b1bff)\
$cmd_duration\
$status\
$battery\
\n$character"""

[username]
style_user = "fg:#FFD84C bg:#1b1b1bff"
style_root = "fg:#FF4C8B bg:#1b1b1bff"
format = "[ $user ]($style)"
show_always = true

[hostname]
style = "fg:#f7f1ff bg:#1b1b1bff"
format = "[@$hostname ]($style)"
ssh_only = false

[directory]
style = "fg:#1b1b1bff bg:#47CFFF"
format = "[ $path ]($style)"
truncation_length = 2
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "

[os]
disabled = false
style = "bg:#D36CFF fg:#1b1b1bff"

[os.symbols]
Windows = " 󰍲 "
Ubuntu = " 󰕈 "
SUSE = "  "
Raspbian = " 󰐿 "
Mint = " 󰣭 "
Macos = " 󰀵 "
Manjaro = "  "
Linux = " 󰌽 "
Gentoo = " 󰣨 "
Fedora = " 󰣛 "
Alpine = "  "
Amazon = "  "
Android = "  "
Arch = " 󰣇 "
Artix = " 󰣇 "
CentOS = "  "
Debian = " 󰣚 "
Redhat = " 󱄛 "
RedHatEnterprise = " 󱄛 "
Pop = "  "


[git_branch]
symbol = ""
style = "bg:#1b1b1bff"
format = "[[ $symbol $branch ](fg:#f7f1ff bg:#1b1b1bff)]($style)"

[git_status]
style = "bg:#1b1b1bff"
format = "[[($all_status$ahead_behind )](fg:#f7f1ff bg:#1b1b1bff)]($style)"

[git_metrics]
disabled = true

[nodejs]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#47CFFF bg:#69676c)]($style)"

[rust]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#47CFFF bg:#69676c)]($style)"

[golang]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#47CFFF bg:#69676c)]($style)"

[php]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#47CFFF bg:#69676c)]($style)"

[java]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#47CFFF bg:#69676c)]($style)"

[julia]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#47CFFF bg:#69676c)]($style)"

[ocaml]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#47CFFF bg:#69676c)]($style)"

[zig]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#47CFFF bg:#69676c)]($style)"

[lua]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#47CFFF bg:#69676c)]($style)"

[python]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#47CFFF bg:#69676c)]($style)"

[ruby]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#47CFFF bg:#69676c)]($style)"

[dart]
symbol = ""
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#47CFFF bg:#69676c)]($style)"

[c]
symbol = "󰬊"
style = "bg:#69676c"
format = "[[ $symbol ($version) ](fg:#47CFFF bg:#69676c)]($style)"

[time]
disabled = false
time_format = "%R"
style = "bg:#FF4C8B"
format = "[[  $time ](fg:#1b1b1bff bg:#FF4C8B)]($style)"

[cmd_duration]
min_time = 800
style = "bg:#1b1b1bff"
format = "[[  $duration ](fg:#47CFFF bg:#1b1b1bff)]($style)"

[status]
disabled = false
style = "bg:#1b1b1bff"
format = "[[ $status ](fg:#FF4C8B bg:#1b1b1bff)]($style)"

[memory_usage]
disabled = true

[battery]
disabled = false
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""
format = "[[ $symbol $percentage ](fg:#FFD84C bg:#1b1b1bff)]($style)"

[[battery.display]]
threshold = 20
style = "fg:#FF4C8B bg:#1b1b1bff"

[[battery.display]]
threshold = 100
style = "fg:#FFD84C bg:#1b1b1bff"

[character]
success_symbol = "[❯](bold #7FFFD4)"
error_symbol = "[❯](bold #FF4C8B)"
