[colors]
background = "#000000"
foreground = "#cccccc"
cursor = "#cccccc"
selection-background = "#333333"
selection-foreground = "#cccccc"
black = "#000000"
red = "#999999"
green = "#bbbbbb"
yellow = "#dddddd"
blue = "#888888"
magenta = "#aaaaaa"
cyan = "#cccccc"
white = "#ffffff"
light-black = "#333333"
light-red = "#bbbbbb"
light-green = "#dddddd"
light-yellow = "#ffffff"
light-blue = "#aaaaaa"
light-magenta = "#cccccc"
light-cyan = "#eeeeee"
light-white = "#ffffff"
