[colors]
background = "#200b0a"
foreground = "#f7f1ff"
cursor = "#f7f1ff"
selection-background = "#525053"
selection-foreground = "#f7f1ff"
black = "#200b0a"
red = "#fc618d"
green = "#7bd88f"
yellow = "#ffed89"
blue = "#47e6ff"
magenta = "#ff9999"
cyan = "#47e6ff"
white = "#f7f1ff"
light-black = "#525053"
light-red = "#fc618d"
light-green = "#7bd88f"
light-yellow = "#ffed89"
light-blue = "#47e6ff"
light-magenta = "#ff9999"
light-cyan = "#47e6ff"
light-white = "#f7f1ff"
