[colors]
background = "#f8fafe"
foreground = "#544d40"
cursor = "#544d40"
selection-background = "#b0a999"
selection-foreground = "#544d40"
black = "#f8fafe"
red = "#1faa9e"
green = "#733d9a"
yellow = "#2e70ad"
blue = "#b55a0f"
magenta = "#3e9d21"
cyan = "#bd4c3d"
white = "#544d40"
light-black = "#b0a999"
light-red = "#009e91"
light-green = "#5a1f8a"
light-yellow = "#0f5ba2"
light-blue = "#b23b00"
light-magenta = "#218c00"
light-cyan = "#b32e1f"
light-white = "#000000"
