[colors]
background = "#ffffff"
foreground = "#333333"
cursor = "#333333"
selection-background = "#333333"
selection-foreground = "#333333"
black = "#ffffff"
red = "#333333"
green = "#444444"
yellow = "#555555"
blue = "#666666"
magenta = "#777777"
cyan = "#888888"
white = "#333333"
light-black = "#333333"
light-red = "#444444"
light-green = "#555555"
light-yellow = "#666666"
light-blue = "#777777"
light-magenta = "#888888"
light-cyan = "#999999"
light-white = "#aaaaaa"
