[colors]
background = "#fafafa"
foreground = "#1a1a1a"
cursor = "#1a1a1a"
selection-background = "#4d4d4d"
selection-foreground = "#1a1a1a"
black = "#fafafa"
red = "#990026"
green = "#007a28"
yellow = "#8a6408"
blue = "#007a9e"
magenta = "#4d2699"
cyan = "#007a9e"
white = "#1a1a1a"
light-black = "#4d4d4d"
light-red = "#990026"
light-green = "#007a28"
light-yellow = "#8a6408"
light-blue = "#007a9e"
light-magenta = "#4d2699"
light-cyan = "#007a9e"
light-white = "#1a1a1a"
