[colors]
background = "#000000"
foreground = "#f7f1ff"
cursor = "#f7f1ff"
selection-background = "#69676c"
selection-foreground = "#f7f1ff"
black = "#000000"
red = "#FF4C8B"
green = "#7FFFD4"
yellow = "#FFD84C"
blue = "#00FFA8"
magenta = "#D36CFF"
cyan = "#47CFFF"
white = "#f7f1ff"
light-black = "#69676c"
light-red = "#FF4C8B"
light-green = "#7FFFD4"
light-yellow = "#FFD84C"
light-blue = "#00FFA8"
light-magenta = "#D36CFF"
light-cyan = "#47CFFF"
light-white = "#f7f1ff"
