[colors]
background = "#1a0a30"
foreground = "#f7f1ff"
cursor = "#f7f1ff"
selection-background = "#c4bdff"
selection-foreground = "#f7f1ff"
black = "#1a0a30"
red = "#fc618d"
green = "#7bd88f"
yellow = "#fce566"
blue = "#a3f3ff"
magenta = "#c4bdff"
cyan = "#a3f3ff"
white = "#1a0a30"
light-black = "#c4bdff"
light-red = "#fc618d"
light-green = "#7bd88f"
light-yellow = "#fce566"
light-blue = "#a3f3ff"
light-magenta = "#c4bdff"
light-cyan = "#a3f3ff"
light-white = "#f7f1ff"
