[colors]
background = "#1a1a1a"
foreground = "#ffffff"
cursor = "#ffffff"
selection-background = "#6272A4"
selection-foreground = "#ffffff"
black = "#1A1A1A"
red = "#FF5555"
green = "#B8E6A0"
yellow = "#FFE4A3"
blue = "#BD93F9"
magenta = "#FF9AA2"
cyan = "#8BE9FD"
white = "#FFFFFF"
light-black = "#6272A4"
light-red = "#FF6E6E"
light-green = "#B8E6A0"
light-yellow = "#FFE4A3"
light-blue = "#D6ACFF"
light-magenta = "#FF9AA2"
light-cyan = "#A4FFFF"
light-white = "#FFFFFF"
