[colors]
background = "#1c1c1d"
foreground = "#f7f1ff"
cursor = "#f7f1ff"
selection-background = "#1c1c1d"
selection-foreground = "#f7f1ff"
black = "#1c1c1d"
red = "#fc618d"
green = "#7bd88f"
yellow = "#fce566"
blue = "#fd9353"
magenta = "#948ae3"
cyan = "#5ad4e6"
white = "#f7f1ff"
light-black = "#1c1c1d"
light-red = "#fc618d"
light-green = "#7bd88f"
light-yellow = "#fce566"
light-blue = "#fd9353"
light-magenta = "#948ae3"
light-cyan = "#5ad4e6"
light-white = "#f7f1ff"
